# 基础配置
app:
  port: 8080
database:
  driver: postgres
  source: "host=localhost port=5432 user=postgres password=postgres dbname=gin_db sslmode=disable"
redis:
  addr: localhost:6379
  password:
  db: 0
log:
  format: json
  level: debug
  report_caller: false
